assets: /home/lythk/safe-flow-matching/safelibero/libero/libero/assets
bddl_files: /home/lythk/safe-flow-matching/safelibero/libero/libero/bddl_files
benchmark_root: /home/lythk/safe-flow-matching/safelibero/libero/libero
datasets: /home/lythk/safe-flow-matching/safelibero/libero/datasets
init_states: /home/lythk/safe-flow-matching/safelibero/libero/libero/init_files_training
